name: Checkmarx Sarif Integration

# Controls when the workflow will run
on:
  push:
    branches:
      - master
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkmarx scan
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://sng.ast.checkmarx.net
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          cx_tenant: ${{ secrets.CX_TENANT }} # This should be replaced by users' tenant name
          project_name: 'GSS_Willie_Test'
          # Branch name
          branch: 'github_report'
          additional_params: --report-format sarif --output-path . --output-name SARIF_REPORT

      - name: Upload Checkmarx Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Report
          path: SARIF_REPORT.sarif
