name: CxFlow
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run CxFlow Scan
        shell: pwsh
        env:
          CHECKMARX_USERNAME: ${{ secrets.CHECKMARX_USERNAME }}
          CHECKMARX_PASSWORD: ${{ secrets.CHECKMARX_PASSWORD }}
        run: |
          java -jar C:\CxFlow\cx-flow-1.7.09.jar `
            --scan `
            --f="." `
            --project="Github_Report" `
            --checkmarx.team="CxServer" `
            --checkmarx.username="$env:CHECKMARX_USERNAME" `
            --checkmarx.password="$env:CHECKMARX_PASSWORD" `
            --cx-flow.enabled-vulnerability-scanners=sast `
            --cx-flow.bug-tracker=GITHUBPULL `
            --namespace=${{ github.repository_owner }} `
            --repo-name=${{ github.event.repository.name }} `
            --branch=${{ github.ref_name }} `
            --checkmarx.settings-override=true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cx.sarif

      - name: Upload Checkmarx Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Report
          path: cx.sarif
